format = """
$directory\
$line_break\
$character"""

[directory]
style = "blue"
truncate_to_repo = false
truncation_length = 69420

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"
